language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
env:
  - PIP_DJANGO='Django>=1.7,<1.8'
  - PIP_DJANGO='Django>=1.8,<1.9'
install:
  - "pip install $PIP_DJANGO"
  - "pip install pyyaml coveralls"
  - "pip install -e ."
script:
  coverage run runtests.py
after_success:
  coveralls
