language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO_BRANCH=stable/1.4.x
  - DJANGO_BRANCH=stable/1.5.x
  - DJANGO_BRANCH=master
install:
  - "pip install -e git+git://github.com/django/django.git@$DJANGO_BRANCH#egg=django"
  - "pip install pyyaml"
script:
  ./runtests.py
